### PR TITLE
Adding Generic instance for HugeInt

### PR DESCRIPTION
**Pull request by ethul**
Would you consider accepting this PR to add a Generic instance for HugeInt?

Thanks!

### CODE REVIEW

**Comment by chexxor** [comment]
Should be OK, as we added Generic instances for other types in this lib - https://github.com/purescript-contrib/purescript-precise/pull/6

**Comment by garyb** [comment]
I think maybe this should just be `derive` rather than `derive newtype`... `derive newtype` for `Generic` seems suspect to me since the derived values will be indistinguishable from the generics for the underlying type, so I don't know if they'll behave right when trying to examine/reconstruct something. I could be wrong though, if you've tried it out and it works as expected, then I guess it's fine!

**Comment by ethul** [comment]
I think you bring up a good point. Let me verify by looking at both derive by itself and derive newtype. I will provide an update on this later today or tomorrow.

**Comment by ethul** [comment]
You're right that with the `newtype` we get `tag: "Data.HugeNum.HugeNum"` instead of `tag: "Data.HugeInt.HugeInt"`. The Generic instance with the `derive newtype` is working, but perhaps in the spirit of `purescript-precise` the second choice is a more fitting implementation. I will make the change!

**Comment by garyb** [comment]
Thanks!

**Comment by ethul** [comment]
Thank you!

**Pull request merged**
